POST localhost:8888/users
Accept: application/json
Content-Type: application/json

{
  "id": "A65D5411-6E04-4501-9B60-E94053BCD72B",
  "email": "mateusz.koziol@houseofangular.io",
  "name": "mkoziol"
}
