version: "3.9"

services:
  idp:
    restart: always
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - purple-clouds-network

  nginx-idp:
    restart: always
    image: nginx:stable
    ports:
      - "8888:8888"
    depends_on:
      - idp
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - purple-clouds-network

networks:
  purple-clouds-network: