version: "3.9"

services:
  mailer:
    restart: always
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "9001:9000"
    volumes:
      - .:/var/www/html
    networks:
      - purple-clouds-network

  nginx-mailer:
    restart: always
    image: nginx:stable
    ports:
      - "8889:8889"
    depends_on:
      - mailer
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - purple-clouds-network

networks:
  purple-clouds-network: